### ISSUE TITLE
Default bias correction for (co)variance differs from Base and OnlineStats

### ISSUE THREAD

**Issue by annuges** [gdkrmr/WeightedOnlineStats.jl#38]
The (co)variance estimator in this package returns the uncorrected variance by default while both Base and OnlineStats return the corrected value.
Since it is a part of the tests I assume this was an explicit choice, is there something about the weighted statistics that makes its preferable to return the uncorrected value by default?

In the below example (with the same value for all weights) this feels a bit  unintuitive to me.
```
using OnlineStats, WeightedOnlineStats, StaticArrays, Statistics

data=rand(10,3)
weights=ones(10)
c=CovMatrix()
cw=WeightedCovMatrix()
fit!(c, eachrow(data))
fit!(cw, eachrow(data), weights)

@assert cov(c) ≈ cov(cw) ≈ cov(data) #fails

@assert cov(c) ≈ cov(cw,corrected=true) ≈ cov(data) #passes
```

**Comment by gdkrmr** [comment]
@meggart any opinion on this? I would change it to match `OnlineStatsBase.jl` if there is no objection. I am asking because technically this is a breaking change. 

I don't really consider this a big issue because the correction will not really change by much if there are many values and you are supposed to use this package with many values.

**Comment by meggart** [comment]
Yes, no problem with changing this from my side.

**Comment by gdkrmr** [comment]
Done.
